import type { NextPage } from 'next';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useUser } from '../../context/UserContext';

import Loader from '../../components/Loader';
import Footer from '../../components/Footer';
import Workout from '../../components/Workout';
import Navbar from '../../components/Navbar';
import PrivateRoute from '../privateRoute';

const Start: NextPage = () => {
    const { todaysWorkout } = useUser();
    const router = useRouter();

    useEffect(() => {
        if (!todaysWorkout) {
            router.push('/dashboard');
        }
    }, []);

    return (
        <PrivateRoute>
            <div>
                <Head>
                    <title>Daily HIIT - Start</title>
                    <meta name='description' content='Generated by create next app' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <Navbar />
                {todaysWorkout ? <Workout /> : <Loader />}
                <Footer />
            </div>
        </PrivateRoute>
    );
};

export default Start;
