import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useAuth } from '../context/AuthUserContext';
import Head from 'next/head';

import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import HomeInfo from '../components/HomeInfo';
import AppFeatures from '../components/AppFeatures';
import Footer from '../components/Footer';
import { useEffect } from 'react';

const Home: NextPage = () => {
    const router = useRouter();
    const { authUser } = useAuth();

    useEffect(() => {
        if (authUser) {
            router.push('/dashboard');
        }
    }, [authUser]);

    return (
        <div>
            <Head>
                <title>Daily HIIT</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Navbar />
            <Hero />
            <HomeInfo />
            <AppFeatures />
            <Footer />
        </div>
    );
};

export default Home;
