import type { NextPage } from 'next';
import Head from 'next/head';

import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import HomeInfo from '../components/HomeInfo';
import AppFeatures from '../components/AppFeatures';
import Footer from '../components/Footer';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Daily HIIT</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Navbar />
            <Hero />
            <HomeInfo />
            <AppFeatures />
            <Footer />
        </div>
    );
};

export default Home;
