import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../../components/Navbar';
import WorkoutCategory from '../../components/WorkoutCategory';
import Footer from '../../components/Footer';
import PrivateRoute from '../privateRoute';

const Workouts: NextPage = (props) => {
    return (
        <PrivateRoute>
            <div>
                <Head>
                    <title>Daily HIIT - Workouts</title>
                    <meta name='description' content='Generated by create next app' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <Navbar />
                <WorkoutCategory />
                <Footer />
            </div>
        </PrivateRoute>
    );
};

export default Workouts;
